[package]
name = "publish-test-a-60e894818a"
version = "0.5.1"
edition = "2021"
description = "Just trying crate publishing through CI"
license = "MIT OR Apache-2.0"
repository = "https://github.com/CBenoit/actions-tests"
